version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: node:14
    ports:
      - "3000:3000"
    environment:
      - PG_DB=mydatabase
      - PG_USER=  
      - PG_PASSWORD=password
      - PG_HOST=node_db
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
    volumes:
      - node_db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - node_db

volumes:
  node_db_data: {}


